### ISSUE TITLE
Pluralsight Links Not Found

### ISSUE THREAD

**Issue by willydavidjr** [aspnet/AspNetDocs#156]
# Before you open an issue

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

Both Pluralsight links:
* [Start Free Trial](https://app.pluralsight.com/microsoft/olt/subscribe/SubscriptionRedirector.aspx?freetrial=true&utm_source=microsoft&utm_medium=sponsored-page&utm_content=webmatrix&utm_campaign=microsoft-sponsored-course)
and 
* [Subscribe Now](https://app.pluralsight.com/microsoft/OLT/subscriptions.aspx?utm_source=microsoft&utm_medium=sponsored-page&utm_content=webmatrix&utm_campaign=microsoft-sponsored-course)
 cannot be found.

**Comment by Rick-Anderson** [comment]
Can you provide the URL to the doc?
