### ISSUE TITLE
API Browser: APIs for ASP.NET Core 3.0 Preview are missing

### ISSUE THREAD

**Issue by ryanmajidi** [aspnet/AspNetDocs#162]
**Moved from [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1521)**

Description
Many APIs appear to be missing from ASP.NET Core 3.0.

Repro Steps

Search for "httprequest" in ASP.NET Core 2.2
A. https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.2&term=httprequest
B. Many results, including the second result Microsoft.AspNetCore.Http.HttpRequest I was searching for
Repeat search in ASP.NET Core 3.0
A. https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.0&term=httprequest
B. Only 3 results, and Microsoft.AspNetCore.Http.HttpRequest is missing

Submitted by @mikeharder

**Comment by ryanmajidi** [comment]
@Rick-Anderson Can you please take a look at this?

**Comment by Rick-Anderson** [comment]
We're working on this.

**Comment by Rick-Anderson** [comment]
If you want to create an issue, do so in the [ASP.NET Core repo](https://github.com/aspnet/AspNetCore.Docs/issues)
