### ISSUE TITLE
Tutorial mistake: Following example of default 'Authentication' on project creation does not create necessary controllers

### ISSUE THREAD

**Issue by banta-isaiah** [aspnet/AspNetDocs#167]
In the second image of the [Getting started with ASP.NET MVC 5](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/getting-started) tutorial under the subsection [Create your first app](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/getting-started#create-your-first-app), **No Authentication** is, by default, selected. 

![image](https://user-images.githubusercontent.com/19816813/59291910-bbe24d80-8c30-11e9-87c0-3e0d2d6b733f.png)

And is referenced in the following [Adding a Controller](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/adding-a-controller) section here: 

![image](https://user-images.githubusercontent.com/19816813/59291818-876e9180-8c30-11e9-92bf-626230cc6555.png)

Which states that Home, Account, and Manage controllers were created with the default option in the previous page of the tutorial. 

However, Account and Manage controllers are only created if the _Individual User Accounts_ option is selected. 
![image](https://user-images.githubusercontent.com/19816813/59291680-40809c00-8c30-11e9-873d-a9a4aba2070c.png)

Otherwise, the default option only creates the Home controller.

**Comment by banta-isaiah** [comment]
I would be happy to fix this! But have a couple of questions: 

Would I need to include new text explaining the needed Authentication choice? 

Or, would I need to include new image(s) reflecting the change and instructions? 

In which case: 
- would I need to get images from 2017 VS?
- or, would I need to submit 2019 images (and then update the rest of the tutorial?)

I'm happy to do either!

**Comment by Rick-Anderson** [comment]
@banta-isaiah  can you update with VS19 images.

I would change the note to say something like

If you selected **Individual User Accounts**,  manage and account controllers would also be created.
