### ISSUE TITLE
Improvements to storing secrets in config files

### ISSUE THREAD

**Issue by lostphenomenon** [aspnet/AspNetDocs#218]
#196 Issue description
Related to: [best pratices for sensitive data](https://github.com/aspnet/AspNetDocs/blob/master/aspnet/identity/overview/features-api/best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure.md)

In case of web.configs the articles suggest that the best practice would be adding an external file (AppSettingsSecrets.config in this sample) and storing the passwords there while not adding the file into source control. In my opinnion it doesn't differ if they are in a separate file or in the web.config, if someone hacks the server they can just be read in plain text. If we would go by the article we would worry much more about someone trying to do something malicious with our code repository than our actual hosting server/application.

Instead this part of the article should suggest some best practices or possible solutions on how to store them in an encrypted manner. A plain example would be for this to store hashes and decrypt them when reading the configuration in application code, but i'm positive that there are much better solutions.

If anyone could improve on this that would be a huge plus for many of us!

**Comment by Rick-Anderson** [comment]
@lostphenomenon  please provide the link to best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure.md

What is `#196` ?

**Comment by lostphenomenon** [comment]
> @lostphenomenon please provide the link to best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure.md
> 
> What is `#196` ?

Its an increment that was automatically attached.

**Comment by Rick-Anderson** [comment]
@lostphenomenon  #196 resolves to a PR LocalizationFix: Fixes that has nothing to do with this.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
