### ISSUE TITLE
Update ASP.NET Web Deployment

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetDocs#232]
Retire [ASP.NET Web Deployment using Visual Studio: Deploying to Test](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/deploying-to-iis) and redirect to [Create an ASP.NET Core web app in Azure](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet)

**Comment by Rick-Anderson** [comment]
@tdykstra  are you OK with this?

**Comment by tdykstra** [comment]
Yes.

**Comment by Rick-Anderson** [comment]
I think I'll keep this and at the top provide a link to the core version.
