### ISSUE TITLE
Is the mvc music store still applicable to core 3.0 is there a successor tutorial

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetDocs#266]
@surfmuggle asked at https://github.com/aspnet/AspNetCore.Docs/issues/15721 ...

> It would be helpful if the docs page for the music store tutorial would contain a remark
>
> * if this tutorial is still relevant for Core 3.0
> * or if there is a successor
>
> If a successor exists a link would be nice.

... for the doc at ...

https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/mvc-music-store/mvc-music-store-part-1

**Comment by Rick-Anderson** [comment]
Music store tutorial has never been available for ASP.NET Core - any version. It was not even updated to the latest version of ASP.NET Framework MVC
