### ISSUE TITLE
Need example using ASP.NET Identity via REST API

### ISSUE THREAD

**Issue by karezza** [aspnet/AspNetDocs#299]
Need example using ASP.NET Identity via REST API.  Something that shows how to use ASP.NET Identity without the GUI interface.  Seems that if I wanted to create my own page to gather credentials there should be a method to call into ASP.NET Identity to register.  My project does not currently use a GUI, but I'd still like to take advantage of not having to reinvent the wheel with all that ASP.NET Identity has to offer with registration/tables/database/custom attributes to go along with user, tokens to pass via an Authorization header.

- Explain why this topic is needed.
Searching the net leads to many examples where folks appear to have gone through your tutorial and then created their own duplicate blog.  New project, add authentication type, browsing to page now asks you to register, cool tables have appeared in your database ...  I currently have an existing REST API using IdentityModel configured to use ADFS.  I'd like to switch to using ASP.NET Identity.  Following the existing example I can add packages from nuget but I'm not sure which methods to call.  I did find an article that partially had methods to call (missing link at the moment) but even after adding nuget libraries I could not get the methods to resolve.

- Suggest a location in the Table of Contents.
On this page: https://docs.microsoft.com/en-us/aspnet/identity/overview/
After the link 'Adding ASP.NET Identity to an Empty or Existing Web Forms Project'

- Write an abstract. In one **short** paragraph, describe what this topic will cover.
Adding ASP.NET Identity to an Empty or Existing Web app project.  Though one of the main features provided by ASP.NET Identity is the ability to gather credentials in a standard way, there is still value to using ASP.NET Identity with an API-only project.  A common use case for this is an on-premise solution that is being moved into the cloud and shared with customers.   Here we will give an example which adds ASP.NET to a project via nuget, calls the register method of ASP.NET Identity to create a new user, acquires a token for a user with the new user/password, calls a method using said token, then finally logging out the user.  (Also an example of a custom field being get/set.)

- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
As I'm new to ASP.NET Identity, I'm not sure what will go here.  You the owners of the project will need to bring your wealth of knowledge to the plate.  I'm sure this will help with bringing more of the heavy hitter API developers to use ASP.NET Identity.  Later I probably will use the GUI style to create a page to integrate with ASP.NET Identity, but even then my backend will still need to be able to access ASP.NET identity via the Authorization header (and to acquire the custom fields).

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/AspNetCore.Docs/pull/15288/files

We don't have a team to update the docs in this repo.
